# Generated by Django 2.2.26 on 2022-04-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0007_auto_20200828_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='ass_coordinator',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='template',
            name='ass_manager',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='template',
            name='name_coordinator',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='name_manager',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
