# Generated by Django 2.2.26 on 2022-04-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0008_auto_20220411_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='ass_coordinator',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='ass_manager',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_coordinator',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_manager',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
