# Generated by Django 2.2.26 on 2022-04-21 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0010_auto_20220421_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='location',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='80'),
        ),
    ]
