# Generated by Django 2.2.26 on 2022-05-12 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0011_template_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='px_coordinator',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='template',
            name='px_manager',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
