# Generated by Django 2.2.26 on 2022-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0013_auto_20220530_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='ass_coordinator',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='ass_manager',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_coordinator',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_manager',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='template',
            name='pos_coordinator',
            field=models.CharField(max_length=70, verbose_name='Cargo Coordenador'),
        ),
        migrations.AlterField(
            model_name='template',
            name='pos_manager',
            field=models.CharField(max_length=70, verbose_name='Cargo Diretor'),
        ),
    ]
