# Generated by Django 2.2.26 on 2022-09-20 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_auto_20220531_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='day',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='80'),
        ),
        migrations.AddField(
            model_name='template',
            name='month',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='80'),
        ),
        migrations.AddField(
            model_name='template',
            name='year',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='80'),
        ),
    ]
