# Generated by Django 2.2.26 on 2022-05-31 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0014_auto_20220531_1019'),
        ('certificates', '0013_auto_20220517_2322'),
    ]

    operations = [
    ]
