# Generated by Django 2.2.26 on 2022-09-21 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0015_merge_20220531_1815'),
        ('certificates', '0015_auto_20220920_2033'),
    ]

    operations = [
    ]
