# Generated by Django 2.2.26 on 2022-11-06 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_merge_20221105_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='has_manualSignature',
            field=models.BooleanField(default=False, verbose_name='Não, a imagem de fundo já possui as assinaturas'),
        ),
    ]
