# Generated by Django 2.2.26 on 2022-11-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0017_template_has_manualsignature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='ass_coordinator',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='ass_manager',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_coordinator',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='name_manager',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='template',
            name='pos_coordinator',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Cargo Coordenador'),
        ),
        migrations.AlterField(
            model_name='template',
            name='pos_manager',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Cargo Diretor'),
        ),
    ]
