# Generated by Django 2.2.26 on 2022-11-09 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0016_merge_20220921_0205'),
        ('certificates', '0018_auto_20221108_1055'),
    ]

    operations = [
    ]
