# Generated by Django 2.2.26 on 2022-09-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210205_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='day',
            field=models.CharField(blank=True, max_length=255, verbose_name='dia de emissão do certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='month',
            field=models.CharField(blank=True, max_length=255, verbose_name='mês de emissão do certificado'),
        ),
        migrations.AddField(
            model_name='event',
            name='year',
            field=models.CharField(blank=True, max_length=255, verbose_name='ano de emissão do certificado'),
        ),
    ]
